messager/chats/urls.py
from django.urls import path
from .views import DialogsView, CreateDialogView, MessagesView, DeleteMessages

app_name = 'chats'

urlpatterns = [
    path('', DialogsView.as_view(), name='list'),
    path('create/<int:user_id>/', CreateDialogView.as_view(), name='create'),
    path('<int:chat_id>/', MessagesView.as_view(), name='messages'),
    path('<int:chat_id>/delete/', DeleteMessages.as_view(), name='delete'),
]

messager/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import Index, Login, Logout

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Index.as_view(), name='index'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('users/', include('messager.users.urls')),
    path('chats/', include('messager.chats.urls')),
]

messager/users/urls.py
from django.urls import path
from .views import CreateUser, UserList

app_name = 'users'

urlpatterns = [
    path('', UserList.as_view(), name='list'),
    path('create/', CreateUser.as_view(), name='create'),
]

messager/chats/models.py
from django.db import models
from messager.users.models import User
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
 
 
class Chat(models.Model):
    DIALOG = 'D'
    CHAT = 'C'
    CHAT_TYPE_CHOICES = (
        (DIALOG, _('Dialog')),
        (CHAT, _('Chat'))
    )
 
    type = models.CharField(
        _('Тип'),
        max_length=1,
        choices=CHAT_TYPE_CHOICES,
        default=DIALOG
    )
    members = models.ManyToManyField(User, verbose_name=_("Участник"))
    new_message = models.BooleanField(_('Есть новые сообщения'), default=False)


class Message(models.Model):
    chat = models.ForeignKey(Chat, verbose_name=_("Чат"), on_delete=models.CASCADE)
    author = models.ForeignKey(User, verbose_name=_("Пользователь"), on_delete=models.CASCADE)
    message = models.CharField(max_length=1000, verbose_name=_("Сообщение"))
    pub_date = models.DateTimeField(_('Дата сообщения'), default=timezone.now)
    is_readed = models.BooleanField(_('Прочитано'), default=False)
 
    class Meta:
        ordering=['pub_date']
 
    def __str__(self):
        return self.message

messager/users/models.py
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy


class User(AbstractUser):

    def __str__(self):
        return self.get_full_name()

    class Meta:
        verbose_name = gettext_lazy('User')
        verbose_name_plural = gettext_lazy('Users')
        ordering = ['id']

messager/chats/forms.py
from django import forms
from .models import Message


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['message']
        labels = {'message': ""}

messager/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User


class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            'username',
            'password1',
            'password2',
        ]

messager/chats/views.py
from django.views.generic import ListView, CreateView, DeleteView
from .models import Chat, Message
from .forms import MessageForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.base import TemplateView
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View
from django.db.models import Count
from django.contrib import auth
from django.utils.translation import gettext_lazy


# Create your views here.
class DialogsView(View):
    def get(self, request):
        chats = Chat.objects.filter(members__in=[request.user.id])
        messages = Message.objects.all()
        return render(request, 'chats.html', {'user_profile': request.user, 'chats': chats, 'messages': messages, 'css_file': gettext_lazy('css/message.css')})


class MessagesView(CreateView):
    def get(self, request, chat_id):
        try:
            chat = Chat.objects.get(id=chat_id)
            if request.user in chat.members.all():
                chat.message_set.filter(is_readed=False).exclude(author=request.user).update(is_readed=True)
            else:
                chat = None
        except Chat.DoesNotExist:
            chat = None
 
        return render(
            request,
            'messages.html',
            {
                'user_profile': request.user,
                'chat': chat,
                'form': MessageForm(),
                'button_text': gettext_lazy('<ion-icon name="paper-plane-outline"></ion-icon>'),
                'css_file': gettext_lazy('css/message.css'),
            }
        )

    def post(self, request, chat_id):
        form = MessageForm(data=request.POST)
        if form.is_valid():
            message = form.save(commit=False)
            message.chat_id = chat_id
            message.author = request.user
            message.save()
        return redirect(reverse('chats:messages', kwargs={'chat_id': chat_id}))




class CreateDialogView(View):

    def get(self, request, user_id):
        chats = Chat.objects.filter(members__in=[request.user.id, user_id], type=Chat.DIALOG).annotate(c=Count('members')).filter(c=2)
        if chats.count() == 0:
            chat = Chat.objects.create()
            chat.members.add(request.user)
            chat.members.add(user_id)
        else:
            chat = chats.first()
        return redirect(reverse('chats:messages', kwargs={'chat_id': chat.id}))


class DeleteMessages(View):

    def get(self, request, chat_id):
        Message.objects.filter(chat=chat_id).delete()
        return redirect(reverse('chats:messages', kwargs={'chat_id': chat_id}))

messager/users/views.py
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.translation import gettext_lazy
from .models import User
from messager.chats.models import Chat
from .forms import UserForm
from django.shortcuts import render


# Create your views here.
class CreateUser(CreateView):
    model = User
    form_class = UserForm
    template_name = 'form.html'
    success_url = reverse_lazy('index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = gettext_lazy('Create')
        context['button_text'] = gettext_lazy('Registration')
        return context

class UserList(LoginRequiredMixin, ListView):
    template_name = 'users.html'
    
    def get_queryset(self):
        self.new_message = Chat.objects.filter(members__in=[self.request.user])
        return self.new_message

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = gettext_lazy('Create')
        context['new_message'] = self.new_message
        context['users'] = User.objects.all()
        return context

class NewMessage(ListView):
    template_name = 'users.html'
    model = Chat
    context_object_name = 'new_message'

    

messager/views.py
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic.base import TemplateView
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy


class Index(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = gettext_lazy('Messager on Django')
        context['sub_title'] = gettext_lazy('You can login to your account or register')
        context['login'] = gettext_lazy('Login')
        context['register'] = gettext_lazy('Register')
        context['open_chat'] = gettext_lazy('Open chat')
        context['logout'] = gettext_lazy('Outlog')
        return context


class Login(LoginView):
    template_name = 'form.html'
    next_page = reverse_lazy('index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = gettext_lazy('Input')
        context['button_text'] = gettext_lazy('Input')
        return context

class Logout(LogoutView):
    next_page = reverse_lazy('index')

messager/templates/chats.html
{% extends 'index.html' %}
{% load i18n %}
{% load bootstrap4 %}
{% load static %}
{% block css_add %}
    <link rel="stylesheet" href="{% static 'chats/css/chats.css' %}">
{% endblock %}
{% block content %}
<div class="panel">
    <div class="button-flex">
        <a href="{% url 'users:list' %}" class="btn btn-primary mb-1 ml-3 mt-1">Create dialog</a>
        <a href="{% url 'logout' %}" class="btn btn-primary mb-1 mr-3 mt-1">Logout</a>
    </div>
    {% if chats.count == 0 %}
        <div class="panel panel-body">{% translate "Нет ни одного начатого диалога" %}</div>
    {% endif %}
    {% for chat in chats %}
            <a class="nav-link" href="{% url 'chats:messages' chat.id %}">
                <ul class="list-group">
                    <li class="chat">
                        <div class="chat-content-item">
                            <div class="last_message_container">
                                {% if chat.members.all.1 is None %}
                                    <p class="h4">Избранное</p>
                                {% else %}
                                    {% for u in chat.members.all %}
                                        {% if u != user %}
                                            <p class="h4">{{ u.username }}</p>
                                        {% endif %}
                                    {% endfor %}
                                {% endif %}
                                <p class="last_message">
                                    {{ chat.message_set.all.last }}
                                </p>
                                {% if not chat.message_set.all.last.is_readed and not chat.message_set.all.last.author == user %}
                                    <span class="rounded-circle new_message"></span>
                                {% endif %}
                            </div>
                        </div>
                    </li>
                </ul>
               <!--<a href="{% url 'chats:delete' chat.id %}">Delete</a>-->
            </a>
    {% endfor %}
</div>
{% endblock %}

messager/templates/form.html
{% extends 'index.html' %}
{% load i18n %}
{% load bootstrap4 %}
{% block content %}
<div class="container wrapper flex-grow-1">
    <h1 class="my-4">{{ title }}</h1>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button button_text button_type="submit" button_class="btn-primary" %}
    </form>
</div>
{% endblock %}

messager/templates/home.html
{% extends 'index.html' %}
{% load i18n %}
{% load bootstrap4 %}
{% block content %}
<div class="container">
    <div class="jumbotron mt-3">
      <h1>{{ title }}</h1>
      {% if user.is_authenticated %}
        <p class="lead">Hi, {{ user.username }}!</p>
        <a class="btn btn-lg btn-primary" href="{% url 'chats:list' %}" role="button">{{ open_chat }}</a>
        <a class="btn btn-lg btn-primary" href="{% url 'logout' %}" role="button">{{ logout }}</a>
      {% else %}
        <p class="lead">{{ sub_title }}</p>
        <a class="btn btn-lg btn-primary" href="{% url 'login' %}" role="button">{{ login }}</a>
        <a class="btn btn-lg btn-primary" href="{% url 'users:create' %}" role="button">{{ register }}</a>
      {% endif %}
    </div>
</div>
{% endblock %}

messager/templates/index.html
{% load i18n %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style type="text/css">
        body{
            background: rgb(245, 245, 245);
        }
    </style>
    {% block css_add %}{% endblock %}
</head>
<body class="d-flex flex-column min-vh-100">
    <div class="container wrapper flex-grow-1">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

messager/templates/message.html
{% load i18n %}
{% load static %}
{% load bootstrap4 %}
{% block css_add %}
    <link rel="stylesheet" href="{% static 'chats/css/message.css' %}">
{% endblock %}
{% block content %}
{% load tz %}
        {% if message_item.author.username == user.username %}
            <div class="text-right">
                <div class="text-dark alert alert-success p-2" role="alert">
                        {{ message_item.message|safe }}
                    {% if message.is_readed is True %}
                        <ion-icon class="text-primary" name="checkmark-done-outline"></ion-icon>
                    {% else %}
                        <ion-icon class="text-primary" name="checkmark-outline"></ion-icon>
                    {% endif %}
                    <p class="text-muted mb-0 time">{{ message_item.pub_date.time }}</p>
                </div>
                
            </div>
        {% else %}
            <div>
                <div class="text-dark alert alert-light p-2" role="alert">
                    {{ message_item.message|safe }}
                    <p class="text-muted mb-0 time">{{ message_item.pub_date.time }}</p>
                </div>
            </div>
        {% endif %}
{% endblock %}

messager/templates/messages.html
{% extends 'index.html' %}
{% load i18n %}
{% load bootstrap4 %}
{% load static %}
{% block css_add %}
    <link rel="stylesheet" href="{% static 'chats/css/messages.css' %}">
{% endblock %}
{% block content %}
<div class="background border rounded">
    <div class="background-user p-1 border-bottom border-primary">
        <a class="link back" href="{% url 'chats:list' %}"><ion-icon name="arrow-back-outline"></ion-icon></a>
        {% for u in chat.members.all %}
            {% if u != user %}
                <span class="h3 mb-0">{{ u.username }}</span>
            {% endif %}
        {% endfor %}
        <a class="link basket" href="{% url 'chats:delete' chat.id %}"><ion-icon name="trash-outline"></ion-icon></a>
    </div>
    <div class="container messages mt-2">
        {% for message in chat.message_set.all %}
            {% include 'message.html' with message_item=message %}
        {% endfor %}
    </div>
    <form id="messages" class="mt-1 p-2 form-post" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button button_text button_type="submit" button_class="btn-primary" %}
    </form>
</div>

<script>
    const form_control = document.querySelector('.form-control');
    form_control.setAttribute('autocomplete', 'off');
    form_control.focus()

    const messages = document.querySelector('.messages')
    console.log(messages)
    messages.scrollTop = messages.scrollHeight;
</script>
<script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
{% endblock %}

messager/templates/users.html
{% extends 'index.html' %}
{% load i18n %}
{% load static %}
{% load bootstrap4 %}
{% block content %}
<div class="container">
    <div class="my-3 p-3 bg-body rounded shadow-sm">
        <h6 class="border-bottom pb-2 mb-0">С кем бы хотел создать диалог</h6>
        {% for user in users %}
        <a class="nav-link" href="{% url 'chats:create' user.id %}">
          <div class="d-flex pt-3 mb-3 border border-secondary rounded list-group-item-action">
            <img class="ml-2 mr-2" src="{% static 'users/img/sheep.png' %}" width="25px" height="25px" alt="">
            <p class="pb-3 mb-0 small lh-sm">
              <strong class="h5 d-block text-gray-dark">{{ user.username }}</strong>
            </p>
          </div>
        </a>
        {% endfor %}
      </div>
</div>
{% endblock %}